// ============ aa docs agents-md(接入引导片段)============
import Foundation
import Darwin
import AAContracts

/// `aa docs <主题>`。目前只有 `agents-md`:输出可整段贴进任意仓库 AGENTS.md 的 markdown 片段。
/// 纯文档,不连宿主(agent 离线也能取);指令文本英文。
func dispatchDocs(_ rest: [String]) -> Never {
    guard let topic = rest.first else {
        errPrint("用法: aa docs agents-md   输出可贴进仓库 AGENTS.md 的接入片段(markdown)")
        exit(AAExitCode.usage)
    }
    switch topic {
    case "agents-md":
        outPrint(agentsMarkdownSnippet())
        exit(AAExitCode.success)
    case "-h", "--help":
        outPrint("用法: aa docs agents-md   输出可贴进仓库 AGENTS.md 的接入片段(markdown)")
        exit(AAExitCode.success)
    default:
        errPrint("未知 docs 主题: \(topic)")
        errPrint("用法: aa docs agents-md")
        exit(AAExitCode.usage)
    }
}

/// AGENTS.md 接入片段(英文,面向 Codex 等外部 agent)。必含:何时用 / 发现·调用 / 退出码 / dangerous 语义 / prefix_rule 信任配置。
func agentsMarkdownSnippet() -> String {
    return """
    <!-- BEGIN aa CLI integration — generated by `aa docs agents-md` -->
    ## Using the `aa` CLI (agent-facing proxy/agent control)

    `aa` is the command surface for the local AA menu-bar agent host. Whenever you
    (an AI coding agent such as Codex) need to inspect or operate the local proxy
    or any registered capability, call `aa` instead of editing system settings
    directly.

    ### When to use `aa`

    - The task involves the proxy, the agent host, or any registered capability
      (status, mode, node, subscription, ...).
    - You need to discover which operations this machine actually supports.
    - You want a stable, machine-readable result you can branch on.

    If the task does not touch the agent/proxy, you do not need `aa`.

    ### Discover & call

    Discovery and invocation share one registry-backed surface. Every command
    accepts `--json` for stable machine-readable stdout; human diagnostics go to
    stderr.

    ```
    aa capabilities list --json                           # enumerate capabilities (id, risk, summary, schema)
    aa capabilities describe <id> --json                  # full structured schema (parameters) for one capability
    aa capabilities call <id> --input '<json>' --json     # invoke with a JSON input object
    ```

    Ergonomic domain sub-commands map registry metadata onto `<domain> <verb...>`
    and run through the exact same path as `capabilities call` (same route, same
    response envelope, same exit codes). Named flags are coerced to each
    parameter's declared type:

    ```
    aa demo echo --message hi --json
    # behaves identically to:
    aa capabilities call demo.echo --input '{"message":"hi"}' --json
    ```

    An unknown domain command (`aa <domain> <verb>` that maps to no capability)
    is a usage error: exit `1`, `error.code=unknown_command`. This differs from
    the base API `aa capabilities call|describe <id>` on an unknown capability id,
    which is a protocol/validation error: exit `6`, `error.code=unknown_capability`.

    ### Exit codes (stable contract)

    Branch on the process exit code; the `--json` error envelope carries a finer
    `error.code`.

    - `0`  success
    - `1`  usage error (bad CLI arguments, or an unknown domain sub-command)
    - `2`  denied (a dangerous capability was refused at the host)
    - `3`  timeout
    - `4`  host unreachable (the AA host is not running)
    - `5`  capability business failure
    - `6`  protocol / validation error (unknown capability, missing/typed param)

    On failure with `--json`, stdout is a `{"ok":false,"error":{"code":...,"detail":...}}`
    envelope; on success it is the capability's own JSON output.

    ### Dangerous capabilities

    Capabilities marked `dangerous` (trust-surface changes) require final
    confirmation in the host GUI. The CLI never blocks and never prompts: if the
    user approves, the call proceeds; if they refuse — or no GUI is available —
    the call returns `error.code=denied` with exit code `2`. Do not attempt to
    bypass this; there is no CLI flag that approves a dangerous capability.

    ### Trust setup for a sandboxed Codex (one-time)

    Under Codex's default `workspace-write` sandbox, all local IPC (Unix sockets
    and localhost TCP) is blocked at the syscall level, so `aa` cannot reach the
    host from inside the sandbox. The supported posture is to run `aa` *outside*
    the sandbox via an escalated trust rule scoped to the `aa` prefix:

    - Mark the command escalated: `sandbox_permissions: "require_escalated"`.
    - Scope the persisted trust to the `aa` prefix: `prefix_rule ["aa"]`.

    Codex surfaces this as a persistable allow-rule; approve it once in an
    interactive session. The design intent is that the approval persists across
    sessions, after which `aa ...` runs outside the sandbox with IPC intact.
    Note: the exact persisted config form and its cross-session persistence are
    not yet verified in practice — confirm with that one-time interactive
    approval. If this machine's Codex already runs `danger-full-access`, no
    action is needed. MCP tool calls do not go through the shell sandbox, so a
    future thin MCP adapter over the same registry would sidestep this entirely.
    <!-- END aa CLI integration -->
    """
}
